inherit_from:
  - .rubocop_airbnb.yml

inherit_gem:
  rubocop-discourse: default.yml

#Rails用に最適化
Rails:
  Enabled: true

#rubocopで検証したくないフォルダを指定
AllCops:
  Exclude:
    - 'config/**/*'
    - 'bin/*'
    - 'db/seeds.rb'
    - 'Gemfile'
    - 'vendor/**/*'
