inherit_from:
  - .rubocop_airbnb.yml

#Rails用に最適化
Rails:
  Enabled: true

#文字制限を変更
Metrics/LineLength:
  Max: 120

#rubocopで検証したくないフォルダを指定
AllCops:
  Exclude:
    - 'config/**/*'
    - 'bin/*'
    - 'db/*'
    - 'db/**/*'
    - 'spec/*'
    - 'Gemfile'
    - 'vendor/bundle/**/*'
