default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: <%= ENV['DEV_DATABASE'] %>

test:
  <<: *default
  database: <%= ENV['TES_DATABASE'] %>

production:
  <<: *default
  database: <%= ENV['PRO_DATABASE'] %>
